services:
  - type: web
    name: dvorpay
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dvorpay-db
          property: connectionString
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: dvorpay-db
    databaseName: dvorpay
    user: dvorpay
    plan: free